### ISSUE TITLE
add support for "ip" in addition to "arp"

### ISSUE THREAD

**Issue by reefland** [mudape/iphonedetect#10]
The arp command is being deprecated on Linux systems.  The new command appears to be "ip neigh", the output format is slightly different than the "arp -na", looks like you will have to alter which column you look at for IP address and MAC address.

```
$ ip neigh
192.168.0.250 dev enp8s0 lladdr 00:25:90:dd:15:dd STALE
192.168.0.253 dev enp8s0 lladdr 00:1b:a9:17:b3:5a REACHABLE
192.168.0.1 dev enp8s0 lladdr 48:5d:36:f0:12:2a REACHABLE
192.168.0.251 dev enp8s0 lladdr 78:e1:03:9c:a7:6d STALE
```

**Comment by mudape** [comment]
Thanks @reefland,
I'll look in to it.

**Comment by reefland** [comment]
Any thoughts on supporting both? Look for "ip" and if not found look for "arp" ??  Home Assistant runs nicely on non-linux systems like BSD which will still be using "arp".  I can't speak directly to Mac's but pretty sure they still use older tools as well.
