### ISSUE TITLE
There is a warning in HA 2024.1b

### ISSUE THREAD

**Issue by gieljnssns** [mudape/iphonedetect#101]
```
Logger: homeassistant.components.device_tracker
Source: helpers/deprecation.py:204
Integration: Device tracker (documentation, issues)
First occurred: December 29, 2023 at 17:09:30 (2 occurrences)
Last logged: December 29, 2023 at 17:09:30

SOURCE_TYPE_ROUTER was used from iphonedetect, this is a deprecated constant which will be removed in HA Core 2025.1. Use SourceType.ROUTER instead, please create a bug report at https://github.com/mudape/iphonedetect/issues
```

**Comment by wobeco** [comment]
Logger: homeassistant.components.device_tracker.const
Source: helpers/deprecation.py:**205**
Integration: Geräte-Tracker (documentation, issues)
First occurred: 13:40:13 (1 occurrences)
Last logged: 13:40:13

SOURCE_TYPE_ROUTER was used from iphonedetect, this is a deprecated constant which will be removed in HA Core 2025.1. Use SourceType.ROUTER instead, please create a bug report at https://github.com/mudape/iphonedetect/issues

**Comment by naimadfpv** [comment]
https://github.com/mudape/iphonedetect/pull/102

there is already a pull request waiting to be merged to solve that problem.

**Comment by mudape** [comment]
Thank you @gieljnssns !
