### ISSUE TITLE
A device is permanently "not_home" - but the integration writes same records into DB

### ISSUE THREAD

**Issue by ildar170975** [mudape/iphonedetect#105]
Here is a "states" table for some "device_tracker".
It is always `not_home`.
Check the "attributes_id" column - these are same attributes.

![изображение](https://github.com/mudape/iphonedetect/assets/71872483/777cb0d2-39c4-4f0b-a177-4d551bce5cbe)

Believe these attributes are these:

![изображение](https://github.com/mudape/iphonedetect/assets/71872483/0ef574e1-6b29-4d19-9734-e2ecefea2ba7)

Why the integration is writing smth into DB when it is not needed?

**Comment by mudape** [comment]
Don't know about the records
Note that apple watch can't be tracked by wifi as its not directly connected to your network

In version 2.2.0 a coordinator is used, did that change anyting?

**Comment by ildar170975** [comment]
@mudape 
Thanks for the feedback!
I will start monitoring & report then.

**Comment by ildar170975** [comment]
@mudape 
Test with some iPhone which can be `home` / `not_home`:

![изображение](https://github.com/mudape/iphonedetect/assets/71872483/8441a8f2-e338-4d63-9944-5ab971e97df4)

These records have same `attributes_id` (i.e. same attributes).
The last column is a converted `last_updated`.
HA was restarted 3 times - yellow rows correspond to these moments.
Seems that the entity was marked as "updated" on HA startup - even with same content (state & attributes); probably this is how HA works.

Result: I do not see a behaviour described in the 1st post.
In the 1st post there were same records with different `last_updated` and HA was NOT restarted during a period with many repeated consecutive records.
Closing the issue.

Data from DB were taken by DBBrowser for SQLite.

**Comment by ildar170975** [comment]
@mudape 
> Note that apple watch can't be tracked by wifi as its not directly connected to your network

Strange, when I installed iPhone detect 1st time (2021?) - noticed that it reported `home` for apple watch.
