### ISSUE TITLE
Created iphonedetect devices are associated with ASUSWRT also

### ISSUE THREAD

**Issue by ildar170975** [mudape/iphonedetect#106]
Here is a page of my `iphonedetect` integration.
It contains 5 devices (2 tablets, 2 phones, 1 watch):
![image](https://github.com/mudape/iphonedetect/assets/71872483/5be6208c-5fc1-4f53-892d-afd409c576a9)

If "ASUSWRT" integration is opened, it shows some `iphonedetect` devices as well (2 phones, 2 tablets):

![image](https://github.com/mudape/iphonedetect/assets/71872483/facd4329-de11-40be-baee-5b3f660ace84)

These added `iphonedetect` devices are somehow associated with 2 integrations:

![image](https://github.com/mudape/iphonedetect/assets/71872483/9bcbb037-17a4-459c-b862-001d336d2605)

This is a page of some `iphonedetect` device:

![image](https://github.com/mudape/iphonedetect/assets/71872483/e4dd8f11-34f8-44e1-a37d-140fce6a20f0)

Here these 2 device_trackers are for ASUSWRT & `iphonedetect` correspondingly.

Imho `iphonedetect` device should not be associated with ASUSWRT.

**Comment by mudape** [comment]
Hi @ildar170975 
They are associated because both have the MAC addresses as connection identifier, they "share" the device

**Comment by ildar170975** [comment]
Hi @mudape 
So, this association with ASUSWRT was not made intentionally, it happened since MAC is used as an identifier. So far I see no negative result of this association, just a confusion.
Probably this “association” can be seen in core.entity_registry. I will check it and come back, may be will get some ideas.

**Comment by ildar170975** [comment]
Imho this is wrong. Device should not be associated with several integrations. I will consult with dev guys & community. Could be also a core issue.

**Comment by nysmag** [comment]
In the pre-release 2.2.x the MAC address and device info has been removed from this integration.
Please let me know if that makes more sense.
Note that you might have to remove/add the iphonedetect entity to "release" the connection. At least ctrl-F5 your browser :P

**Comment by ildar170975** [comment]
Confirm - in 2.2.1 devices are not associated with ASUSWRT.
Very good, thank you!
