### ISSUE TITLE
Setup failed for custom integration `iphonedetect`: No setup or config entry setup function defined.

### ISSUE THREAD

**Issue by ms1design** [mudape/iphonedetect#110]
Version affected: `1.4.1`

<img width="737" alt="Screenshot 2024-03-18 at 10 52 52" src="https://github.com/mudape/iphonedetect/assets/24204300/eeecc593-54b2-49f4-9e82-6a492cb7e851">

**Comment by ms1design** [comment]
@mudape this was from earlier release, but I can’t guarantee thats the previous one was picked correctly. Could it happen that I had version 2.x.x and went from there to 1.4.1 with this error?

**Comment by mudape** [comment]
Ah, yes that's probably it. 
I haven't considered moving from 2 (which do have config entries) back to 1.
Speaking of which the beta needs some love.. I noticed that every other boot HA didn't create the device_tracker entities.
Unclear if it's just my system, to be honest I haven't paid much attention to changes in HA recently.
Will try to find the time.

Meanwhile, could you install the 2.0.5 version again? 
The deprecation warning for source_type_router will return but should work fine until HA 2025.1.

**Comment by ms1design** [comment]
Thanks @mudape, switching back to `2.0.5` helped - now the plugin starts as it was before. 

> I noticed that every other boot HA didn't create the device_tracker entities.
Unclear if it's just my system, to be honest I haven't paid much attention to changes in HA recently.

That's true - I noticed that just because I'm using some hardcoded entities created by this plugin in some of my `scripts` which I use later in `automations`. It's precisely that issue - `device_tracker` entities aren’t created...

**Comment by markfrancisonly** [comment]
> every other boot HA didn't create the device_tracker entities

@mudape I believe the missing entities on restart issue was fixed by implementing async scanner methods ([pr 111](https://github.com/mudape/iphonedetect/pull/111))

**Comment by ms1design** [comment]
@mudape I created a `PR` which I hope should fix issues with `next`/`2.0.5`: https://github.com/mudape/iphonedetect/pull/113

It also covers some fixes in `scanner` methods @markfrancisonly

**Comment by markfrancisonly** [comment]
@ms1design I can't use this integration without support for multiple subnets, feel free to pull out some of the code from pr https://github.com/mudape/iphonedetect/pull/111 and call it your own
