### ISSUE TITLE
No NUD state found for IP

### ISSUE THREAD

**Issue by chgaertner** [mudape/iphonedetect#115]
Dear all,

I am running Home Assistant Core 2024.1.3, Frontend 20240104.0 (Docker) and the pre-release 2.2.1 of iphonedetect (installed manually as the newest version is not yet available in HACS). All devices to track have static IP addresses and I have added them all to the iphonedetect configuration. All devices are accessible via their IP address from a Windows computer and from the Docker host as well.

In Home Assistant all devices are permanentely on "not_home". The log files show hundreds of messages like ...
**2024-03-27 11:34:09.646 WARNING (MainThread) [custom_components.iphonedetect.scanner] No NUD state found for IP: '192.168.1.87'**
... for all the IP addresses I want to track.

As I am running HA as a Docker container, the IP address of the container itself is 172.23.0.2, which means it is a different network than my WiFi (192.168.1.xxx). But I just double checked, I can ping the devices to track from within the Docker container, so they are reachable through the Docker host.

Does anyone of you have an idea what the reason could be?

Greeting from Vienna,
Christian

**Comment by mudape** [comment]
Hi @chgaertner 
Sorry for logging that as a warning, will be fixed.
Your HASS host can't find an entry for 192.168.1.87 in arp table.

What network are you exposing to the docker container? Note that --network-host is needed 
https://www.home-assistant.io/installation/linux#install-home-assistant-container

**Comment by chgaertner** [comment]
> You can download/install beta releases of integrations via HACS, see https://hacs.xyz/docs/faq/beta

Thank you Magnus, I did not know this. :-)

**Comment by chgaertner** [comment]
> Hi @chgaertner Sorry for logging that as a warning, will be fixed. Your HASS host can't find an entry for 192.168.1.87 in arp table.
> 
> What network are you exposing to the docker container? Note that --network-host is needed https://www.home-assistant.io/installation/linux#install-home-assistant-container

Thank you, Magnus, this did solve my problem! In fact I had the "network_mode: host" line in my docker-compose.yml file in the past but for some reason I seem to have removed it. And until now I had no problems without it ...

The warning log entry does not bother me, I just added it to the post because I thought it might be helpful for solving my problem and I wanted to submit a report with all information that might be relevant.

Greetings, Christian
