### ISSUE TITLE
entities disapear on ha reboot

### ISSUE THREAD

**Issue by koburg** [mudape/iphonedetect#117]
the tracker entities disappear on reboot off HA 
if the device is not precent on the network.

why is there not created an "empty" entity so 
I can build automations when device come back ?

i have been testing both 1.4xxx and beta 2.xxx

**Comment by mudape** [comment]
@koburg 
Can't recall why 1.x needs to see the device before the entity is created (some HA thing), but for recent 2.x they should be created.
Please give it a try
