### ISSUE TITLE
Detect by DNS

### ISSUE THREAD

**Issue by roisec** [mudape/iphonedetect#121]
Hi, 
Thanks for your project.
I have a local internal DHCP and DNS server, and I want to understand why this plugin will not be able to work with DNS.
Sometimes, the internal IP is changed, and the DNS server automatically points to the new IP, so your plugin can detect them automatically without changing the IP manually.

Thanks

**Comment by mudape** [comment]
Hi @roisec 
I didn't try using DNS, especially since iOS do not send a host name when phone is using private mac.
To me you're trying to move the "static" address from DHCP to DNS which I don't think many others will.

**Comment by TippyLion28** [comment]
I would also like to know why hostname is not supported. Is this a technical limitation or self-imposed?

I don’t use private MAC address on my home network so my device registers its hostname just fine
