### ISSUE TITLE
Updated to 1.20 with HACS - wiped out all files & directory

### ISSUE THREAD

**Issue by DavidFW1960** [mudape/iphonedetect#15]
As per the title, I just updated using HACS and the entire folder/directory was deleted. Reinstalled and it's still not updating the component. Manually downloaded it now and it seems ok.

**Comment by DavidFW1960** [comment]
also seeing this in my logs now:
```
2020-01-30 09:21:12 ERROR (SyncWorker_5) [homeassistant.loader] Error parsing manifest.json file at /config/custom_components/iphonedetect/manifest.json: Expecting value: line 6 column 18 (char 165)
```

**Comment by DavidFW1960** [comment]
Codeowner needs to be double quoted.
```
{
  "domain": "iphonedetect",
  "name": "iPhone Device Tracker",
  "documentation": "https://github.com/mudape/iphonedetect",
  "dependencies": [],
  "codeowners": ["@mudape"],
  "requirements": [],
  "homeassistant":"0.94.0"
} 
```
Should be correct. I was going to do a PR but the json file in code page doesn't have that anyway.....

**Comment by DavidFW1960** [comment]
1.2.1 also does it... when I update in HACS it deletes the folder. Might be HACS?

**Comment by mudape** [comment]
Same for me. 
Not sure what is going on, hopefully can check tomorrow

**Comment by mudape** [comment]
Hmm, I made more copy-paste errors, in the hacs.json zip-release was true.
Removing the hacs.json file didn't help so now I've added the Action in github to publish a zip-file.
Please try upgrading to 1.2.2

**Comment by DavidFW1960** [comment]
Ah! All good now. I wasn't sure if it was this component or HACS as many weird things with HACS not updating cards at the moment. Glad you fixed it.
