### ISSUE TITLE
update to 1.2.1

### ISSUE THREAD

**Issue by matteos1** [mudape/iphonedetect#18]
after update to new version 1.2.1 give an error after restart of home assistant.. 
Platform error device_tracker.iphonedetect - Integration 'iphonedetect' not found

**Comment by mudape** [comment]
Hi,
I made an error when adding the hacs.json file I added in 1.2.0 (zip-release was set to true).
Should be fixed in 1.2.2.
Please upgrade to that release

**Comment by mudape** [comment]
Hi @matteos1 
Have you upgraded and did that solve the issue?

**Comment by mudape** [comment]
Fixed in #15

**Comment by matteos1** [comment]
yes work
