### ISSUE TITLE
iPhonedetect 1.2.1 detects phone as present when away

### ISSUE THREAD

**Issue by P-Verbrugge** [mudape/iphonedetect#19]
I manually installed the addon, as the installation through HACS breaks (see the other issues).

The problem however is that my phone is detected as home, when I am actually in the office and not home at all. I run the new addon in a test setup. The old version in my live HA version is working just fine and detects my phone as away.

**Comment by mudape** [comment]
Hi,
Hmm. Probably the 'ip neigh' lookup makes wrong conclusion.
Currently this integration only checks if command finds the IP, not the actual state.
Works fine in my setup (HassOs and Asus router).

Could you please check in your network the different output of 'ip neign' when the device away/home?

**Comment by P-Verbrugge** [comment]
How can I exactly check ip neign?

**Comment by mudape** [comment]
Do you have the SSH Terminal add-on?
Enter that and give command `ip n`

To only view your device IP : `ip n|grep 192.168.1.123`
(replace with actual IP of course)

To continuously look, enter `watch 'ip n|grep 192.168.1.123'`
Exit with ctrl-c

**Comment by P-Verbrugge** [comment]
When I am home the result is:
192.168.0.25 dev eth0 lladdr x:x:x:x:x:x REACHABLE

When I am not home:
192.168.0.25 dev eth0 lladdr x:x:x:x:x:x STALE

**Comment by P-Verbrugge** [comment]
In version 1.2.2 everything is fine again.

**Comment by gieljnssns** [comment]
@mudape I'm seeing the same even on 1.2.2
Hassio generic install on an intel nuc (Buster)
```
bash-5.0# ip n|grep 192.168.79.8
192.168.79.8 dev eno1 lladdr xx:xx:xx:xx:29:2f ref 1 used 0/0/0 probes 1 REACHABLE
bash-5.0# ip n|grep 192.168.79.8
192.168.79.8 dev eno1 lladdr xx:xx:xx:xx:29:2f ref 1 used 0/0/0 probes 1 DELAY
bash-5.0# ip n|grep 192.168.79.8
192.168.79.8 dev eno1 lladdr xx:xx:xx:xx:29:2f ref 1 used 0/0/0 probes 1 PROBE
bash-5.0# ip n|grep 192.168.79.8
192.168.79.8 dev eno1  used 0/0/0 probes 3 FAILED
bash-5.0# ip n|grep 192.168.79.8
192.168.79.8 dev eno1  used 0/0/0 probes 6 FAILED
bash-5.0# arp -na|grep 192.168.79.8
? (192.168.79.8) at <incomplete> on eno1
bash-5.0# arp -na|grep 192.168.79.8
? (192.168.79.8) at <incomplete> on eno1
bash-5.0# arp -na|grep 192.168.79.8
? (192.168.79.8) at xx:xx:xx:xx:29:2f [ether] on eno1
bash-5.0#
```

**Comment by gieljnssns** [comment]
And when reinstalling  1.1.0
```
Platform error: device_tracker - Integration 'iphonedetect' not found.
```

**Comment by mudape** [comment]
Hi @gieljnssns,

Version 1.1.0 probably won't install as HACS tries to download a zip-release and there is none for that release.

Please make a new issue if problem with 1.2.2 persist.
