### ISSUE TITLE
iPhonedetect 1.2.2 after updated to Home Assistant 0.105.1 stopped tracking

### ISSUE THREAD

**Issue by SentryMax** [mudape/iphonedetect#23]
Running Hassio on Ubuntu 18.04.3 LTS. Updated last night, have reinstalled iPhonedetect,  reset router, restarted Hassio and still not tracking

**Comment by mudape** [comment]
Hi,

I haven't upgraded yet. Did see a note about device_tracker in the release notes:

> We no longer show device_tracker entities in generated mode. We advise you to bind one or more device trackers to a person that will be shown in the UI.

Is the state updated in Developer States -> States ?

**Comment by SentryMax** [comment]
Fix it by rebooting the Linux box and deleting the "ide_entity: true". you can close it
