### ISSUE TITLE
Phone reports as “Away - 6 hours ago”

### ISSUE THREAD

**Issue by jcqrs** [mudape/iphonedetect#24]
The last update for one phone was six hours ago. I have “consider_home: 60” in my config and was working beautifully until today.

Is there a scan interval I should include?

edit, update: last check was 2 mins ago, STILL shows as “Away” even after waking up the phone and held it in front of the router.

**Comment by mudape** [comment]
Yes, there is a scan_interval but seems to be broken :/

Don't think that's the problem here though. See issue #21

**Comment by mudape** [comment]
Hi @jcqrs,

Can you please upgrade to latest release and check if state is better reported now?
If its still wrong, please activate debug-logging and post results here.
Thanks

**Comment by mudape** [comment]
Stale
