### ISSUE TITLE
Add home zone coordinates to entities with state `home`

### ISSUE THREAD

**Issue by bieniu** [mudape/iphonedetect#28]
I don't sure if it's an issue or feature request. Other device trackers (for example nmap) add home zone coordinates to entities with state `home`. Thanks to this, these entities are displayed on the map card.
![image](https://user-images.githubusercontent.com/478555/75421284-3592a680-593a-11ea-9a27-992a2db66908.png)

iphonedetect doesn't work that way.
![image](https://user-images.githubusercontent.com/478555/75421553-d3867100-593a-11ea-99dc-405a0a414e88.png)

**Comment by mudape** [comment]
As mentioned in the PR:
- This is a router tracker.
- Device in zone home don't show on the map.
- Other trackers can be added to the Person for same function.
