### ISSUE TITLE
If iPhone is away on HA restart - logs

### ISSUE THREAD

**Issue by Siege36** [mudape/iphonedetect#32]
If an iPhone is away on HA restart, the homeassistant log is filled with:

```
2020-05-01 08:30:48 ERROR (MainThread) [homeassistant.core] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/hass/homeassistant/custom_components/iphonedetect/device_tracker.py", line 94, in update_interval
    host.update(see)
  File "/home/hass/homeassistant/custom_components/iphonedetect/device_tracker.py", line 77, in update
    if self.detectiphone():
  File "/home/hass/homeassistant/custom_components/iphonedetect/device_tracker.py", line 51, in detectiphone
    aSocket.sendto(message, addr)
OSError: [Errno 64] Host is down
```
about every 30 seconds. Would it be possible to edit this to a higher debug level. To me this is inconsequential.

**Comment by mudape** [comment]
Hi @Siege36,

Thanks for reporting, sorry to hear you are having issues.
[`OSError: [Errno 64] Host is down`](https://www.google.com/search?q=OSError%3A+%5BErrno+64%5D+Host+is+down&oq=OSError%3A+%5BErrno+64%5D+Host+is+down&aqs=chrome..69i57j69i58.1242j0j7&sourceid=chrome&ie=UTF-8) indicates that you have network related problems.

How are you running Home-Assistant and do you have any other integrations reporting errors at startup?

There are no deeper network logging available in this integration.
Try [setting ](https://www.home-assistant.io/integrations/logger/#service-set_level)homeassistant.core to debug. Be prepared to be spammed...

**Comment by Siege36** [comment]
I’m am running homer assistant core on a freenas box. No other issues with anything, no errors in the log. Iphonedetect seems to be working fine also, just a lot of errors in the logs I was hoping to clean up.

**Comment by mudape** [comment]
Ok, nice. I have never used that.
I did a quick search and looks like others on FreeNAS has had 'host is down' issue with other applications.
Maybe there is something in Jail causing this, like allow_raw_sockets ?

**Comment by mudape** [comment]
Inactive, closing
