### ISSUE TITLE
ip: command not found

### ISSUE THREAD

**Issue by duvalale** [mudape/iphonedetect#33]
Hello,

When installing iphonedetect on my Home Assistant, I have the following error :
`/bin/sh: ip: command not found`

My config : Home Assistant 0.110.3 on Mac OS Catalina.

Is this package compatible with MacOS ?

**Comment by mudape** [comment]
Hello @duvalale,
Interesting, I was hoping it should work :)

Unfortunately I don't have any experience or access to MacOS.
The integration is supposed to try with command _arp_ if _ip_ fails... Does that work for you?

**Comment by mudape** [comment]
The error you found didn't come from this integration.
Can you please activate debug logging?

Go to Developer Tools -> Services
Call service `logger.set_level` with service data: `custom_components.iphonedetect: debug`

Then check `Load Full Home Assistant Log` under Developer Tools -> Logs

If/when you get output, reset the logger to info using the step above.
A found device might look like:

DEBUG (SyncWorker_3) [custom_components.iphonedetect.device_tracker] ip n output for hostname1 is: 192.168.1.90 dev eth0 lladdr f0:98:9d:c6:xx:xx ref 1 used 0/0/0 probes 1 REACHABLE

Please report any findings here!
