### ISSUE TITLE
Question - Will this also work with an Apple Watch?

### ISSUE THREAD

**Issue by mikesalz** [mudape/iphonedetect#34]
This looks very cool for iOS.  Wondering if it also works for watchOS/Apple Watch?  Thanks!

**Comment by mikesalz** [comment]
@mudape Thoughts?

**Comment by mudape** [comment]
Hi @mikesalz,
Thanks for reaching out.

I don't own an Apple Watch, nor any visiting friends.
Did a quick search and it doesn't seem like the Watch connects to Wifi in a reliable traceable way?
See [info from Apple](https://support.apple.com/en-us/HT204562)

> Your Apple Watch uses Bluetooth when your iPhone is near, which conserves power.  
> If Bluetooth isn’t available, your Apple Watch will try to use Wi-Fi. For example, if compatible Wi-Fi is available and your iPhone isn't in Bluetooth range, your Apple Watch uses Wi-Fi.

> Your Apple Watch can connect to a Wi-Fi network: 
> 
> - If your iPhone, while connected to your watch with Bluetooth, has connected to the network before.
> - If the Wi-Fi network is 802.11b/g/n 2.4GHz.

So, no I don't think tracking an Apple Watch with this integration is possible.
Please try and report back though :)
Think you need a bluetooth tracker, like [room-assistant](https://www.room-assistant.io/)

**Comment by mikesalz** [comment]
Thanks for getting back to me.  You are right - The Apple Watch does not seem to work with this integration, unfortunately.  Question: Is there a way to rename the entity_id?  For example, I'd like to change device_tracker.hostname1 to something more user friendly, like device_tracker.mikes_iphone?

**Comment by mudape** [comment]
Hi,

- Yes, the _hostname1_ was just ment as an example. Use lower case and _ for space.
As an alternative you can customize the name in Home-Assistant/Lovelace.

- consider_home is a Home-Assistant setting for how long the device is unreachable before being marked as away...Strange variable name! The purpose is to prevent false state if a device temporally 
 isn't responding.

- I haven't found any drainage of the battery in our household (we have four different kind of iPhones ranging from 7 to 11).

**Comment by mikesalz** [comment]
Thanks for for all of your help!  I appreciate it!
