### ISSUE TITLE
No creation of known devices file after configuring the yaml file

### ISSUE THREAD

**Issue by TarikTS** [mudape/iphonedetect#35]
Hi ! 
First of all, i did tried this custom components on hass.io with hacs installed, and the best i can say is that it worked perfectly and thanks for that. 

Due to some problems with my SD card, i had to make a new instance of Raspbian and i wanted to try full installation on docker-compose (Home assistant core and separate components) 

No problems for the hacs installation and for the installation of this component

I did configured as your example: 
`device_tracker:
  - platform: iphonedetect
    consider_home: 60
    scan_interval: 12
    new_device_defaults:
      track_new_devices: true
    hosts:
      tarik: 192.168.1.100`

There is no known_devices file even after reinstalling, restarting and switching on and off my device several times. 

The only thing i know is when i install the custom component, it's under root:root privileges and home assistant is under another user and group (in this way, i don't think it can be a problem as root can create files everywhere..

**Comment by mudape** [comment]
Hi @TarikTS,

Thanks for reporting!
Cool, I haven't tested to use other installation then Home-Assistant(Hass.io)  on Raspberry (3 and 4).

Feels like the integration doesn't find your device, hence the know_devices.yaml is written to.
Can you see if you get any output by setting the logger to debug for this integration?

_(As you probably already know, your user needs to be in advanced mode for this setting)_
Go to Developer Tools -> Services
Call service `logger.set_level` with service data: `custom_components.iphonedetect: debug`

 
Then check _Load Full Home Assistant Log_ under Developer Tools -> Logs

If/when you get output, reset the logger to info using the step above.
A found device might look like:

> DEBUG (SyncWorker_3) [custom_components.iphonedetect.device_tracker] ip n output for hostname1 is: 192.168.1.90 dev eth0 lladdr f0:98:9d:c6:xx:xx ref 1 used 0/0/0 probes 1 REACHABLE

Please report any findings here!

**Comment by TarikTS** [comment]
Here are the log that i have: 

> 2020-06-08 23:28:15 DEBUG (SyncWorker_14) [custom_components.iphonedetect.device_tracker] ip n output for tarik is: 
2020-06-08 23:28:15 DEBUG (SyncWorker_14) [custom_components.iphonedetect.device_tracker] Device tarik (192.168.1.100) is AWAY

> 2020-06-08 23:28:28 DEBUG (SyncWorker_1) [custom_components.iphonedetect.device_tracker] ip n output for tarik is: 
2020-06-08 23:28:28 DEBUG (SyncWorker_1) [custom_components.iphonedetect.device_tracker] Device tarik (192.168.1.100) is AWAY

It seems that it cannot find the hostname, 

What i have tried: 

Put the entire home-assistant folder under root 
change the hostname tarik by hostname1

**Comment by mudape** [comment]
Thanks

Yes, looks like the phone can't be found, there is no MAC address found in the output. 
No entry will be made in `known_devices.yaml` until device is 'home'.

Are your (Raspbian/Docker) Home-Assistant on the same network as the phone?
The lookup won't work if HA and the device are on different subnets.

**Comment by TarikTS** [comment]
Hi 
No it isn't, i didn't put the network mode: host on the docker-compose file. I will try that. 

The thing is that when i put the the sonos component and add their ip adress, home-assistant instance still manage to find them. 

I'll try the network mode: host and i will update that

**Comment by mudape** [comment]
Excellent! Thanks for reporting back 😊
