### ISSUE TITLE
Does more than just iphone detect .... consider renaming at publicizing

### ISSUE THREAD

**Issue by GHSTUDIO1** [mudape/iphonedetect#36]
I am using this integration to detect when a computer connects/disconnects.....for example, if the computer is asleep, it disconnects from wifi...when it wakes it is connected.  The states are Home and Not_home which doesn't make sense, but works.  The integration will get wider use if you publicize it as more flexible than just iphone detect.

**Comment by mudape** [comment]
Hi @GHSTUDIO1 

Interesting, I didn't think of that use case. 
This integration is to check if "sleeping" device are on the network, I only thought of smartphones/tablets.
The built-in ping integration has a binary_sensor you can set device class on for nicer states and works fine for computers.

I have heard that other non-iOS devices also responds so I agree a name change would help ppl find the integration.
Any suggestions?

**Comment by jcgoette** [comment]
- "MulticastDNSTracker"
- "mDNSTracker"

?

**Comment by GHSTUDIO1** [comment]
Local network device detector?
LANDeviceTracker

**Comment by mudape** [comment]
Thanks for the name suggestions!

I still think a binary_sensor integration such as Ping is preferred for "stationary" devices as this integration only show home/not home and the other can show connected/not connected.

You can add a [template binary_sensor](https://www.home-assistant.io/integrations/binary_sensor.template/#is-anyone-home) of class connectivity to display connected/not connected

**Comment by ragenhe** [comment]
I'm hoping I have good results testing on my apple watch.

**Comment by mudape** [comment]
Hi @ragenhe,
Apple watch will probably not work with this integration as it primarily connects via another device, not wifi. 
See #34
