### ISSUE TITLE
Consider using `pyroute2` if possible

### ISSUE THREAD

**Issue by bdraco** [mudape/iphonedetect#41]
This would avoid the fork()/exec() overhead of creating the subprocesses

https://github.com/home-assistant/core/issues/40292#issuecomment-726516887

**Comment by mudape** [comment]
Thank you @bdraco , I'll try switch from subprocess to pyroute2 for the 'neighbour lookup'.
Testing the CPU performance is beyond my current knowledge though..

**Comment by mudape** [comment]
[Beta ](https://github.com/mudape/iphonedetect/releases/tag/1.3.0-beta.2)with pyroute2 available which hopefully performs better.

**Comment by bdraco** [comment]
<img width="696" alt="Screen Shot 2020-11-14 at 1 49 01 PM" src="https://user-images.githubusercontent.com/663432/99159413-34e4a080-2680-11eb-8f2e-0577ce0629f3.png">
<img width="426" alt="Screen Shot 2020-11-14 at 1 48 59 PM" src="https://user-images.githubusercontent.com/663432/99159414-3746fa80-2680-11eb-8d31-1e8d137c4740.png">
<img width="426" alt="Screen Shot 2020-11-14 at 1 45 50 PM" src="https://user-images.githubusercontent.com/663432/99159415-37df9100-2680-11eb-8c7c-83b3e67d96e5.png">

Confirmed working as expected.  Will do performance testing next.

**Comment by bdraco** [comment]
Looks good.  All the fork()/exec() overhead is gone.  The python is slightly slower to parse but still the overall call is way faster than creating the subprocesses.

**Comment by gieljnssns** [comment]
Still working for me 
https://github.com/home-assistant/core/issues/40292#issuecomment-727538037

**Comment by bdraco** [comment]
I turns out that linux has only implemented `get` in newer kernels so the overhead of parsing the the whole neighbor table in python can exceed the savings of avoiding the `fork()/exec()` because it still has to enumerate all the entries.  Once the next generation of kernels is in wide use we can use https://github.com/svinota/pyroute2/pull/723

In the mean time it might make sense to limit the existing calls to `nud 2`:

```
root@ha-dev:~/pyroute2# ip neigh show 192.168.212.54
192.168.212.54 dev eth0 lladdr a4:83:e7:74:65:74 STALE
root@ha-dev:~/pyroute2# ip neigh show 192.168.212.54 nud 2
root@ha-dev:~/pyroute2# ip neigh show 192.168.208.1 nud 2
192.168.208.1 dev eth0 lladdr e2:63:da:80:64:6a REACHABLE
root@ha-dev:~/pyroute2# ip neigh show 192.168.208.1 
192.168.208.1 dev eth0 lladdr e2:63:da:80:64:6a REACHABLE
```

**Comment by mudape** [comment]
@gieljnssns 
Are you still seeing this integration using lots of CPU?
Current version 1.3.0 or (pre-release 1.4.0 if you need arp) is only looking at the neighbour table once per update interval.
Maybe that helped?
