### ISSUE TITLE
tracking for different subnets

### ISSUE THREAD

**Issue by nrpetonr** [mudape/iphonedetect#43]
hi mudape, good job, working well on iOS (192.168.7.220) that is in same lan like HA (192.168.7.200), however does not work for iOS (192.168.8.126) that is on different subnet, even though proper IP is defined in yaml. i am not experienced, should this work at all?
hosts:
      luIPHONE: 192.168.8.126
      jiPHONE: 192.168.7.220

p.s. some other integrations that are on different subnet like HA work ok, e.g.
#xiaomi roborock  vacuum  (192.168.8.125) 
vacuum:
  - platform: xiaomi_miio

**Comment by SHxKM** [comment]
I'm running into the same problem, I think. I've got an AP wired to my main router through an ethernet cable. Both my HA and the iPhone are on the AP's wireless network, and `iphonedetect` never picks up the connection..

**Comment by mudape** [comment]
Hi @nrpetonr ,
The tracked devices needs to be on the same subnet as this integration uses the ARP-table on the host.
Please see #8 and other closed issues.

So, sorry this won't work for your setup.

**Comment by nrpetonr** [comment]
thanks anyway. well, icloud and app tracking are remaining options.
