### ISSUE TITLE
[suggestion] is it better also to use the original device tracker from the companion app?

### ISSUE THREAD

**Issue by sunsgs** [mudape/iphonedetect#47]
I like your device_Tracker!
I would like to know if u suggest to have it combined to the orginal tracker from the companion app.

I went to people from the UI and set your tracker plus the original one, but I don't know if it is the best solution to use only your one.

**Comment by mudape** [comment]
Hi @sunsgs,

Thanks, I too think it works fine :)
Yes, the People ability to have multiple trackers is great and this tracker works fine with others.
So, the "best" solution depends on your and other users preference.

Personally I don't use any GPS-trackers as we don't have any need or use for it.
I do use the companion app but only for the GUI and notifications.
Other household members use Homekit to control stuff in Home-Assistant.

Tracking family members 24/7 via GPS feels iffy to me, 
knowing whether their device is home or not enables automation conditions though.
