### ISSUE TITLE
Phone marked as away tre/four times during night

### ISSUE THREAD

**Issue by dtx360** [mudape/iphonedetect#5]
Just installed the component using your recommended config values. I’ve noticed in the log that our iphones is marked as away for a minute about four times during the night. Do you have any recommended tweaks that can be made in the config to possibly reduce these status changes? I know I can combine with gps to stabilize the away status, just checking if tweaks can be made to get better results? Otherwise good work! Much better results than relying on the ubiquity wifi status component I used before trying this.

**Comment by mudape** [comment]
Hey dtx360,
Thanks for reporting!

This has been working so well for us that I actually don't log the device_tracker status anymore...
Looked at the 'person' history for our four tracked users and don't see what you are reporting.
We use iOS 12 and 13, wifi AP from Asus and hass.io runs on a rpi3b.

Could it be that the phones actually do lose wifi when they charge at night?
Maybe an iOS upgrade restarted the phone or the wifi network did something?
If the error persist I would try placing one of the phones in another spot at night and check ubiquity logs to see if there was some issue or maintenance during the time phones are marked away.

**Comment by dtx360** [comment]
Got the phones on the latest IOS 13 versions, one iPhone 7 and one iPhone XR. Running Hass.io in docker on intel hardware. I've checked my network controller logs and updated the AP firmware but it shows no sign of the phones disconnecting or having bad signal strenght in the bedroom at night. Setting the device_tracker consider_home to 120 seems to stabilize the home/away state. I might adjust the interval_seconds parameter to see if I can lower the consider_home parameter... but for now it's stable enough to auto-disable location tracking on the IOS app while home and enable it on away to save battery. And do some simple light scenes. Might even work with the alarm component in conjunction with the motion sensors if the phone runs out of battery while at home. 

Have you tried other values than the standard 12 seconds for scanning interval?

One should probably not rely on one device_tracker platform anyway if you want 100% state tracking i guess. Thanks for the follow-up!

**Comment by mudape** [comment]
HI,

Nice, happy its working for you now!
No, I haven't tried other intervalls, they work fine with our network.

**Comment by mudape** [comment]
consider_home adjusted
