### ISSUE TITLE
Does not seem to be accurate

### ISSUE THREAD

**Issue by popsyann** [mudape/iphonedetect#50]
I just installed this integration and what I can see is that:
  - my son phone is still 'Home' after my son has left since 10 minutes
  - my daughter is 'Away' while she is at home

` - platform: iphonedetect
   consider_home: 60
   scan_interval: 12
   new_device_defaults:
     track_new_devices: true
   hosts:
     pops_iphone: 192.168.86.64
     ibu_iphone: 192.168.86.21
     iqah_iphone: 192.168.86.59
     yam_iphone: 192.168.86.20
     erwan_iphone: 192.168.86.23
`
Obviously, each IP address listed a bove has been 'reserved' in my router.

Any clue?
Best regards

**Comment by mudape** [comment]
Hi @popsyann 
So, two of five devices gives wrong status? That's odd!

Please check in router/dhcp that the devices has been given the IP.
Maybe the users has (de)activated private MAC for your WiFi

You can add more devices, one for the private MAC and one for the regular and add both to People/Person in HA.
Then it won't matter which state the device has
