### ISSUE TITLE
No 'version' key in the manifest file

### ISSUE THREAD

**Issue by arenasa70** [mudape/iphonedetect#52]
Error log shows: 

Logger: homeassistant.loader
Source: loader.py:802
First occurred: 10:20:39 AM (1 occurrences)
Last logged: 10:20:42 AM

No 'version' key in the manifest file for custom integration 'iphonedetect'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'iphonedetect'

**Comment by mudape** [comment]
Thank you @arenasa70, added version in latest release
