### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'ip'

### ISSUE THREAD

**Issue by elyobelyob** [mudape/iphonedetect#53]
Had an upgrade through and now am getting an issue, and am set to 'not_home' constantly ... 

 delete mode 100644 custom_components/iphonedetect/__pycache__/__init__.cpython-37.pyc
 create mode 100644 custom_components/iphonedetect/__pycache__/const.cpython-38.pyc
 delete mode 100644 custom_components/iphonedetect/__pycache__/device_tracker.cpython-37.pyc
 rewrite custom_components/iphonedetect/__pycache__/device_tracker.cpython-38.pyc (82%)
 create mode 100644 custom_components/iphonedetect/const.py

``2021-03-02 13:08:46 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/homeassistant/custom_components/iphonedetect/device_tracker.py", line 94, in update_interval
    Host.find_in_arp(devices, see)
  File "/home/homeassistant/homeassistant/custom_components/iphonedetect/device_tracker.py", line 66, in find_in_arp
    neighbours = subprocess.check_output(cmd, shell=False).decode()
  File "/usr/local/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/local/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ip'``

**Comment by mudape** [comment]
Hi @elyobelyob 
Looks like you run Home-Assistant on platform that doesn't support the 'ip' command.
I removed the fallback to using 'arp' in 1.3.0, maybe I have to put it back..

Please install previous version to restore functionality.

**Comment by elyobelyob** [comment]
Hi, am using TrueNAS, which runs on FreeBSD. In case this helps.

The expert on this implementation is troy, and he may be able to help with integration. https://community.home-assistant.io/t/home-assistant-core-truenas-core-community-plugin/170542

I'm reverting to .25 and will see how this goes. 

Thanks

**Comment by elyobelyob** [comment]
https://github.com/tprelog is his repo ... in case you can start a conversation ... will see if I can find him on Discord ...

**Comment by elyobelyob** [comment]
1.2.5 is working fine again, I also found Troy ... fingers crossed we can keep with your fine work!

**Comment by tprelog** [comment]
Hi @elyobelyob, I'm afraid @mudape is correct

> Looks like you run Home-Assistant on platform that doesn't support the 'ip' command.

If this was just a missing dependency that needed to be installed, I would be happy to add it... Unfortunately, It looks like `ip` is not available on FreeBSD so I'm not sure I can help.

> I removed the fallback to using 'arp' in 1.3.0, maybe I have to put it back..

If it is not too much extra maintenance cost... please do consider

> The expert on this implementation is troy

Let's not go starting rumors :smile: ... I have some experience, yes - but an expert I am not

**Comment by elyobelyob** [comment]
Oops, did I big @tprelog up a bit, well, he deserves it.

**Comment by elyobelyob** [comment]
Thanks both for your help.

**Comment by kai74** [comment]
I have exactly the same issue. I am not sure how to get the older version.?  (Truenas) Maybe someone can help me? :)
@mudape I hope you will consider to put it back. :)

**Comment by elyobelyob** [comment]
Under HACS > Integrations > iphonedetect ... click the kebab menu >
reinstall > choose 1.2.5 from 'Select Version'

**Comment by mudape** [comment]
Hey @elyobelyob , @kai74 

Released (well kind of, messed up but now it's there..) a pre-release that again includes using 'arp'
Please try and report back :)

To install pre-releases in HACS, again make a reinstall. Check show beta and **1.4.0** should be visible after a while

**Comment by elyobelyob** [comment]
Looking good. Am now on 1.4.0 and works great. Thanks.

**Comment by kai74** [comment]
Looks good. Will report back if you find anything. 

Thanks for all great work.

**Comment by kai74** [comment]
Get this message in the log
Logger: custom_components.iphonedetect.device_tracker
Source: custom_components/iphonedetect/device_tracker.py:122 
Integration: iphonedetect (documentation, issues) 
First occurred: 6:51:10 PM (54 occurrences) 
Last logged: 8:18:33 PM

[Errno 64] Host is down

**Comment by mudape** [comment]
Weird, are you seeing other network issues?
Looks like your host can't reach the device's the integration is trying to 'ping'

**Comment by elyobelyob** [comment]
I'm seeing no issues in my log files. Well, nothing in relation to this!

**Comment by kai74** [comment]
Strange, it was no issue before the last update. Not any other issue, other the normally ones. Something's else I can do? 

I am running HA in an Truenas Jail. Can be something there! I’am moving HA to an dedicated machine running HA OS soon, so maybe we should wait and see if it get resolved..

Thanks so far, for all help..

**Comment by elyobelyob** [comment]
I have the same setup as you. TrueNAS jail.

**Comment by kai74** [comment]
Strange. What else can be wrong?

søn. 7. mar. 2021 kl. 11.54 skrev elyobelyob <notifications@github.com>:

**Comment by elyobelyob** [comment]
Make sure you've turned off the iOS thing where they privatise your IP
address.

**Comment by mudape** [comment]
Solved in 1.4
