### ISSUE TITLE
[Question]: iPhone changes its mac address

### ISSUE THREAD

**Issue by agmaq** [mudape/iphonedetect#56]
Hey, 

I have been using this plugin for quite a long time but then it suddenly stopped working... actually it still works, but the "condition" has been changed...

Since iOS14, iPhone periodically changes its MAC address, see e.g. [here](https://www.imore.com/apple-will-have-ios-14-ipados-14-and-watchos-7-randomize-mac-addresses-name-privacy), which I can confirm. Unfortunately, this is an issue because one cannot configure a router to give a device still the same IP address -> which leads to an issue that one would have to change the component settings every time iPhone does such a change.  

Do I miss any configuration or does this change on iPhone side make this component not usable any more for iOS 14+?

Thanks for letting me know. 

-agmaq

**Comment by mudape** [comment]
Hi @agmaq 

I have only seen that iPhones uses **one** 'private address' MAC per network. 
Are you seeing that address change?

What I've done is tracking both MAC addresses, like

```yaml
device_tracker:
  - platform: iphonedetect
    hosts:
      hostname: ip
      hostname_pa: ip
```
Router/DHCP has a reservation/static IP address per MAC.
Then on the [Person ](https://www.home-assistant.io/integrations/person/)in HA add both device_tracker entities.

Other option is to turn off the private address setting in iOS for your home network.
In our house people don't change that setting and the router/dhcp offers the same IP, so actually only one entity is needed.

Of course Apple might have changed the behavior depending on device model or even location.
We have iPhone 7, 11 and 12. All on iOS 14.4 and those still work fine with this integration.

I was playing with fetching IP for the device from DHCP when the hostname gets an offer.
(The hostname doesn't change in iOS regardless of private setting...)
Now that HA has it's own DHCP Discovery I have to reconsider as the listening port is already in use.
Also, if the user changed the iPhone device name (hostname) a new entity would have to be created.

If iOS really do change MAC randomly on already known networks, we have to come up with something new :)

**Comment by agmaq** [comment]
Hi Magnus, 

that private address setting did the job! Amazing! I did not know that it can be disabled - even per a particular wifi network, [here](https://www.howtogeek.com/691955/how-to-disable-private-wi-fi-mac-addresses-on-iphone-and-ipad/).

it would be worth mentioning this in the README.

Thanks a lot and thanks for your reactivity 👍

Best regards

-agmaq
