### ISSUE TITLE
Can't get to work

### ISSUE THREAD

**Issue by SkyHyperV** [mudape/iphonedetect#6]
I can't get this to work...

Latest HA version (101.3)

1. I've created known_devices.yaml with the following:

her_iphone_wifi:
  hide_if_away: false
  icon:
  mac: 
  name: her_iphone_wifi
  picture:
  track: true
me_iphone_wifi:
  hide_if_away: false
  icon:
  mac: 
  name: me_iphone_wifi
  picture:
  track: true

Then in device_tracker directory I have a iphonedetect.yaml using the dir_list in my configuration.yaml so I can split up my yaml configurations:

platform: iphonedetect
consider_home: 60
new_device_defaults:
  track_new_devices: true
  hide_if_away: false
hosts:
  her_iphone_wifi: 10.10.21.220
  me_iphone_wifi: 10.10.21.214

I've reconnected the phones to my WiFi, they have valid static IPs on my network. I see the plugin load but no logs of queries/script running to check.

**Comment by mudape** [comment]
Hi SkyHyperV,
Thanks for reporting!

Hmm, you shouldn't have to manually create known_devices.yaml, only adjust track if it's set to false.

Activate debug to see, well anything, from iphonedetect in the logs
```
logger:
  logs:
    custom_components.iphonedetect: debug
```
In home-assistant.log you should then see something like this at startup.

`[custom_components.iphonedetect.device_tracker] Started iphonedetect with interval=0:00:12 on hosts: 10.10.21.220,10.10.21.214
`

I haven't tried splitting the configuration the way you have. Should work though.
If above doesn't help, can you try instead adding the integration directly in configuration.yaml

**Comment by SkyHyperV** [comment]
I added the logging and this is all that outputs, I'm certain the device_tracker config is right because I have some bluetooth configurations in there that work. Here's the only log that spits out in debug mode with nothing else related to the component.

2019-11-20 14:07:29 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for iphonedetect which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-11-20 14:07:32 DEBUG (SyncWorker_2) [custom_components.iphonedetect.device_tracker] Started iphonedetect with interval=0:00:12 on hosts: 10.10.21.220,10.10.21.214
2019-11-20 14:07:36 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event hacs/repository[L]: id=1337, action=registration, repository=mudape/iphonedetect, repository_id=None>

**Comment by mudape** [comment]
Hi SkyHyperV,
Have you found the issue?
Please note that HA and the phones must be on the same subnet for the arp to succeed.

**Comment by SkyHyperV** [comment]
You're right -- that's why its not working. My HA and Phones are on different subnets, I keep all my HA/home automation stuff on a different VLAN vs my general user population traffic. I'll have to figure out other alternatives to track our phones that may not be as good as your solution but at least work given my setup. Thanks and you can close this!
