### ISSUE TITLE
Add possibility to switch this on/off from HA

### ISSUE THREAD

**Issue by pointlevel** [mudape/iphonedetect#60]
Hi!

Great script, that really works fast and reliable :)
Im not an python-coder myself, so i put my thoughts here. 

What about the possibility to switch the scanner on/off from an input_boolean in HA. My biggest usecase would be that i could turn the scanner off, if no doors are activated. As soon as a door is acivated, the input_boolean gets active and the scanner starts until the boolean turns of again.  This would save some traffic and probably some battery on the devices.
And by just using a simple boolean, we could setup the automations in HA as complex as we want/need that could include cameras, doors or other sensors that would switch the boolean on/off.

With python experience i dont think this would be to difficult to add. And of course (if no boolean is used, same behaviour as now, so no breaking changes)

**Comment by mudape** [comment]
Hi @pointlevel 

I most admit that I don't follow your use case. 
You want to turn of the scanner based on X so you can do Y and then turn it back on if X happens again?

How should the automation know if person 3 of x open/closed the door?

Adding a Boolean to the integration in my opinion only adds complexity which already can be handle in other flows.
Maybe you can have that Boolean as a condition in your automations?
Trigger on person state (home/not home) with condition or a choose on the action?

Regarding saving battery I don't believe this integration effects it that much.
If the phone is outside the network it's none.
Sure, less traffic on the network but a message every 15-30 second isn't anything noteworthy.
