### ISSUE TITLE
Migrate from known_devices.yaml?

### ISSUE THREAD

**Issue by DavidFW1960** [mudape/iphonedetect#61]
Given the ongoing efforts to kill off known_devices.yaml (2021.5.0 migrated the FritzBox integration this release) Have you given any thought to migrating this to use GUI configuration and create the device_tracker rather than relying on known_devices? Because one day this is going to be dead...

**Comment by DavidFW1960** [comment]
> Don't know if adding all devices on the network to HA is a super great thing though... Thoughts?

Yeah that would probably be a pain.. My Fritzbox with the new integration did that but it wasn't that hard to dsable the ones I'm not interested in.

> (no unique_id)

Couldn't that be randomly set anyway?

I do a MAC reservation for my iOS devices here. I guess it would be nice not to have to do that but IP addresses changing can cause other grief anyway.

I was just really wondering if you had given this any thought as it seems the writing is on the wall for known_devices.yaml and has been for a while even though they did allow the life360 to use this fairly recently and there is still a service to manually update a device tracker too....

**Comment by Senbei123** [comment]
@mudape  Any update on making it available by the UI?

**Comment by mudape** [comment]
Can you please try the 2.0.0 pre-release and see if that enables what you are asking for?

For now only the consider home time can be configured once the entity is set up.
You do that in the Configuration -> Devices & Services page in HASS.
Here you also can add (click + and search for iphone device tracker) and delete tracked devices.

After first import you can delete config in configuration.yaml and also remove devices from known_devices.yaml (if not used by other integrations).
Check that Person entity is using the wanted device_tracker as name might have changed.

As the integration don't add entities until MAC is found tracked devices needs to be home before being added the first time.
Thanks!

I haven't updated the readme yet, please report any findings or ideas :)

**Comment by DavidFW1960** [comment]
So sorry I only just realised you sent this. Taking a look now. Thanks.

**Comment by DavidFW1960** [comment]
ok. 2.0.3 loaded. It imported my old config and the entity got a _2 appended to the name. I deleted the yaml config and restarted and renamed the entities. Also deleted from known_devices yaml file. can see it also imported the consider home time I had set in yaml. All working fine. Thanks for this.
