### ISSUE TITLE
Recently stopped working for me

### ISSUE THREAD

**Issue by mspinolo** [mudape/iphonedetect#64]
Not sure when this happened but currently this component is not able to detect my 2 iPhone X running iOS 14.6.

I am running HassOS under Proxmox.

what can I check to dig out what is going on?

**Comment by mudape** [comment]
Sorry to hear that it stopped working, maybe there is something with the X-phone's?
Others has also reported that device, see #63

**Comment by mspinolo** [comment]
So actually it looks like it was me: I added some AP to my network and moved my iphones X on 5ghz network and didn’t realize that’s mean a different MAC address for them…so my router DHCP reservations made such that my iPhone changed IP address.

fixed! So it is not the integration but the user :-)
