### ISSUE TITLE
Ability to ping device by a trigger in Home Assistant

### ISSUE THREAD

**Issue by MiroVerleysen** [mudape/iphonedetect#65]
FEATURE REQUEST

Would be nice to be able to ping a device when a door opens using an automation in Home Assistant. That could potentially make delays smaller.

**Comment by mudape** [comment]
I guess the goal is to know who came/left home when the door opens.
This is already possible with timing the door and device state.
Extra pinging devices on a state of some other entity make no sense to me.
In this case, what if the door is opened by a guest?
