### ISSUE TITLE
Not creating device_tracker

### ISSUE THREAD

**Issue by cris1410** [mudape/iphonedetect#67]
Hi.
I installed this integration using HACS, edit configuration.yaml and add
`device_tracker:
  - platform: iphonedetect
    consider_home: 60
    new_device_defaults:
      track_new_devices: true
    hosts:
      hostname1: 192.168.0.193
      hostname2: 192.168.0.131`

Those ip adresses are assigned as a static in my router.
After reboot I cant find any new device_tracker entity.

Am I missing something?

HA docker 2021.12.10
192.68.0.193 - iPhone 12 mini, iOS 15.1.1
192.168.0.131 - iPhone XR, iOS 15.1

Thank you.

**Comment by mudape** [comment]
Hi,
Your Docker host and HA container needs to be on the same network as the devices you want to track (--network host).
Also, HA needs to be able to create known_devices.yaml in /config so the volume most not be read-only.

**Comment by cris1410** [comment]
Hi,
understood. Thanks ;)

Adam
