### ISSUE TITLE
iphonedetect works well, but automation cannot be used

### ISSUE THREAD

**Issue by lhlxx2010** [mudape/iphonedetect#68]
Iphonedetect works well, but when i want to set automation. I found that i can not find entity(my iphone) in Equipment. I can only find entity(my iphone) in state. Is something i missed?
![eb600dea10c1a4b75e88aacc6f3bbfa](https://user-images.githubusercontent.com/74414383/159693951-c6ba95dd-e3ba-4066-8fe9-1cc9f1bc46a4.png)
![4e7db32ad2be2b586a3f7c1ea77913d](https://user-images.githubusercontent.com/74414383/159693959-710d9a1a-e343-49e4-a5d9-103d3ca73801.png)

**Comment by mudape** [comment]
Hi @lhlxx2010 

device_tracker don't have a Device [https://github.com/home-assistant/core/pull/63328](url)
So, as you've shown the state is needed to act as trigger in automations.
You can use a template with _trigger.to_state.state == "home" (or "not_home")_ for condition and/or action

Maybe a [Device Trigger](https://developers.home-assistant.io/docs/device_automation_trigger) can be added, a device is needed though...

**Comment by mudape** [comment]
Hi @lhlxx2010 
Can you please try the 2.0.0 pre-release and see if that enables what you are asking for?

For now only the consider home time can be configured once the entity is set up.
You do that in the Configuration -> Devices & Services page in HASS.
Here you also can add (click + and search for iphone device tracker) and delete tracked devices.

After first import you can delete config in configuration.yaml and also remove devices from known_devices.yaml (if not used by other integrations).
Check that Person entity is using the wanted device_tracker as name might have changed.

As the integration don't add entities until MAC is found tracked devices needs to be home before being added the first time.
Thanks!

I haven't updated the readme yet, please report any findings or ideas :)
