### ISSUE TITLE
Stopped working in HA 0.102.2

### ISSUE THREAD

**Issue by Stooovie** [mudape/iphonedetect#7]
Hello, this integration stopped working with 0.102.2. I don’t see anything in logs other than “unable to find entity device.tracker…” IP addresses are correct. I also use UPC modem presence sensor for Android phones and that stopped working also, so it's probably something deeper.

Any tips?

**Comment by mudape** [comment]
Hi Stooovie,

I suspect you accidently have spelled device_tracker as device.tracker somewhere in your config

**Comment by Stooovie** [comment]
Hi, that's not it as I didn't change the config at all - problem started right upon upgrading to HA 0.102.2...

**Comment by mudape** [comment]
Maybe you did a change but no restart, and the upgrade restart then triggered this.

“unable to find entity device.tracker…” clearly says there is a misspelling somewhere as the component is device_tracker.
Perhaps you didn't copy/paste that from the log but made the typo here?

As other device_tracker's also stopped working for you, I suggest you check HA forum or Discord for general assistance.
With the information you have given here I can't help you.
