### ISSUE TITLE
Where to configure

### ISSUE THREAD

**Issue by kuduacz** [mudape/iphonedetect#70]
After updated to 2.0. where i can configure entites?

**Comment by mudape** [comment]
Hi @kuduacz 
Thanks for trying the pre-release!

For now only the consider home time can be configured once the entity is set up.
You do that in the Configuration -> Devices & Services page in HASS.
Here you also can add (click + and search for iphone detect tracker) and delete tracked devices.

After first import you can delete config in configuration.yaml and also remove devices from known_devices.yaml (if not used by other integrations).
Check that Person entity is using the wanted device_tracker as name might have changed.

Does that answer your question?

I haven't updated the readme yet, please report any findings or ideas :)

**Comment by kuduacz** [comment]
Hmm. 
Ok, add integrwtion and find all devices whitch i add on configuration.
Ten delete lines on conf file and known devices.
And nie, when i restart HA got notification about integrwtion not loaded properly.

**Comment by kuduacz** [comment]
![image](https://user-images.githubusercontent.com/77231628/163665909-1735ca68-4c03-403b-978d-3ffb3d95cf5b.png)
![image](https://user-images.githubusercontent.com/77231628/163665916-3fb56eec-793e-4de0-8c00-148d35d04533.png)

**Comment by mudape** [comment]
Ah, sorry. I messed up when first releasing and have since adjusted the code under the same version. Was hoping no one had downloaded yet. 
Please redownload the integration in Hacs

You might need to power cycle hass if restarting in the ui doesn't work

Again, sorry!

**Comment by kuduacz** [comment]
unfortunately no results.  the effect is still the same even when I completely removed the integrations

**Comment by mudape** [comment]
Strange, should work after restart of HASS. 
At this time I would recommend reverting back to 1.4.0 as basically no logging is done. 

I have this running on both HASSOS (Rpi4) and on core in docker, must have missed something causing your system not to load the integration.

**Comment by kuduacz** [comment]
Ok. Back to 1.4 ale wait to oficial release and readme😜
Good job anyway.

**Comment by mudape** [comment]
See my silly mistake.. 
I have more device_tracker platforms in my configuration.yaml so didn't catch it before.
For you the code was trying to access stuff that wasn't there so failed.

Hopefully fixed with 2.0.1, please give it a try.
Still no readme..

**Comment by kuduacz** [comment]
Oh! and now it works as it should!
TY.

No entries on configuration yaml and on known devices.
Great job and happy easter!

**Comment by HA-Jon** [comment]
I have this PROBLEM: reset after 2 minutes.

I'm accessing the switch by using a Conbee 2 on HOME ASSISTANT.

What do I need to fix?

**Comment by gieljnssns** [comment]
When trying 2.0.1
```
Deze fout is ontstaan door een aangepaste integratie.

Logger: homeassistant.setup
Source: custom_components/iphonedetect/__init__.py:39
Integration: iPhone Device Tracker (documentation, issues)
First occurred: 17:53:40 (1 occurrences)
Last logged: 17:53:40

Error during setup of component iphonedetect
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 235, in _async_setup_component
    result = await task
  File "/config/custom_components/iphonedetect/__init__.py", line 39, in async_setup
    con_home = int(entry.get(CONF_CONSIDER_HOME, DEFAULT_CONSIDER_HOME))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'datetime.timedelta'
```

**Comment by mudape** [comment]
Thanks for reporting @gieljnssns 
Just pre-released 2.0.2 that hopefully solves it.

Sidenote, I realize imported entities gets suffixed (like device_tracker.phone_2) on import from configuration.yaml
Meaning one still has to update tracked device in Person.
So, maybe not import at all as hands on stuff needs to be done anyhow...

**Comment by gieljnssns** [comment]
@mudape Thanks a lot. This version(2.0.2 and 2.0.3) works as expected. 
I updated, restarted, removed old entities from known files, removed yaml config, restarted, rename all entities(remove _2)

**Comment by mudape** [comment]
> @mudape Thanks a lot. This version(2.0.2 and 2.0.3) works as expected. I updated, restarted, removed old entities from known files, removed yaml config, restarted, rename all entities(remove _2)

Thanks @gieljnssns, both for reporting and the feedback. Very appreciated !

**Comment by Senbei123** [comment]
Hi, still 1.4 to download - when you release version 2.0?

**Comment by ildar170975** [comment]
@mudape 
Thanks a lot for the integration.
I have been using settings in configuration.yaml.
Recently (possible starting from HA 2022.8) the UI settings appeared - got duplicates.
Can I continue using settings in configuration.yaml?
(assume I do not need per-entity defined `consider_home`)
Is using UI config mandatory?

**Comment by mudape** [comment]
Hi @ildar170975 
Config flow for this integration came with its beta release, not HA.
You can downgrade to 1.4 again or continue with what you have now.

I agree configuration.yaml is nice for the setup but as you say stuff if moving away from that, so will this too.

Regarding defining IP in one place I also agree, but do it in your **DHCP** which is the master of the address?
I can add the option to edit the tracked address in UI, actually had that for a while.
It shouldn't change though (looking from this integrations perspective) so I'm ok with the remove/add option.

**Comment by ildar170975** [comment]
> I agree configuration.yaml is nice for the setup but as you say stuff if moving away from that, so will this too.

But developers of integrations are NOT forced to move to UI.
You may support two ways - UI & yaml...
Like it is done for other stuff like "zone", "person" etc.


> Config flow for this integration came with its beta release, not HA.

Strange thing that those errors in log came with 2022.8.0...
Of course, I may be wrong.



> Regarding defining IP in one place I also agree, but do it in your **DHCP** which is the master of the address?

Addresses are defined by DHCP in router based on a static rules (MAC - address).
List of devices' ips is defined in "secrets.yaml", so addresses are available in the whole config.
Addresses are used in many integrations.
So, managing settings in yaml is very flexible.

**Comment by ildar170975** [comment]
At least you can support a "yaml settings keep read from yaml, Ui settings edit in UI" if you want using UI so much.
Check some other integrations: if settings are imported from yaml - they are read-only; only UI-entered settings are available for changing in UI.
