### ISSUE TITLE
Make it possible to find devices on other open subnets

### ISSUE THREAD

**Issue by Aldaran** [mudape/iphonedetect#71]
There is a network with several subnets: smart_home, home_devices, guests, etc. Certain subnets are transparent on my network, and devices on subnets like smart_home and home_devices can see each other well. 
But if the device is on a subnet other than HASS, when I try to add him, I get "IP not in range of HASS subnet".

**Comment by mudape** [comment]
Hi @Aldaran 
That was me trying to be smart and helping users to only add reachable devices, guess its not needed in your case.
Was the previous version of this integration working for you, as in did hass get an arp response?
I added the check as there has been issues where ppl tried to track addresses hass couldn't get mac from.

**Comment by mudape** [comment]
In `config/custom_components/iphonedetect/config_flow.py` comment out or remove lines [43](https://github.com/mudape/iphonedetect/blob/next/custom_components/iphonedetect/config_flow.py#L43) to 45

```python
    if not errors:
        if not IPv4Address(ip) in subnet:
            errors["base"] = "ip_range"
```

Then restart hass, add the entities and see if you can get home/not home status.

**Comment by deeps2k** [comment]
was able to add iPhone now after commenting the code which is on another subnet but getting this "Retrying setup: No MAC address found yet" any pointers? made change to firewall to allow for this ip and for port 5353 , am I  missing some steps

**Comment by mudape** [comment]
Ok, thanks.
The integration checks the ARP table for tracked IP/MAC and in your case HASS (well, pyroute2) can't find any as wanted info is on another network.
That's what the subnet check tries to inform users about as the integration can't tell whether the tracked device is connected or not if never shown in ARP.

You probably need ARP forwarding or some other network tool that is beyond the integration to handle.
Try other integrations, ping maybe?

**Comment by steelman231** [comment]
> In `config/custom_components/iphonedetect/config_flow.py` comment out or remove lines [43](https://github.com/mudape/iphonedetect/blob/next/custom_components/iphonedetect/config_flow.py#L43) to 45
> 
>     if not errors:
>         if not IPv4Address(ip) in subnet:
>             errors["base"] = "ip_range"
> Then restart hass, add the entities and see if you can get home/not home status.

I'm dealing with same problem as OP.
But I can't find those lines in the file. Is there another way around?
