### ISSUE TITLE
[Errno -2] Name does not resolve

### ISSUE THREAD

**Issue by pbu80** [mudape/iphonedetect#72]
All was working fine, Got new Iphone :) 

updated the hostname the hostname, now I get this error in HA

```
Logger: custom_components.iphonedetect.device_tracker
Source: custom_components/iphonedetect/device_tracker.py:122
Integration: iphonedetect (documentation, issues)
First occurred: 6:17:46 PM (23 occurrences)
Last logged: 6:22:10 PM

[Errno -2] Name does not resolve
```

**Comment by mudape** [comment]
Hi @pbu80,
congratz to your new phone!

Looks like something is off in your configuration.yaml
Note that the 'hostname'-side may only contain lower case English letters, no spaces and must start with a letter.

```yaml
device_tracker:
  - platform: iphonedetect
    hosts:
      onlylowercaseandnospaceshere: 192.168.0.123

```

If you're feeling bold, try the beta of this integration :)

- Enable beta version (in HACS, click the dotted meny for this integration, select redownload and check beta versions)
- Upgrade to 2.0.4
  **Important!** Delete entries from `know_devices.yaml` **before** restarting HASS
- Entries in configuration.yaml will be imported on restart
  They will be available in the UI, where you also can add/remove entries.

Once imported you can then also remove the iphonedetect config in configuration.yaml

**Comment by mudape** [comment]
stale
