### ISSUE TITLE
trying to make this work on 2 separate vlan

### ISSUE THREAD

**Issue by thib5** [mudape/iphonedetect#8]
Hi ! I have 2 Vlan in my router, one for my home automation and the other for my personal device. So my home assistant server is on the first one and my iPhone on the other one ... I try to allow trafic in my router between my iPhone and my server but it still not work ... some one know why ?

**Comment by mudape** [comment]
This integration uses arp, so having vlan's usally breaks this as the broadcast isn't made to other subnet.
