### ISSUE TITLE
`consider_home` on 1.4 does not work?

### ISSUE THREAD

**Issue by MacDada** [mudape/iphonedetect#83]
I guess it's not implemented in any way? Or am I missing something? I change it and nothing happens. I also don't see to be used anywhere in the code.

So, the docs for 1.4 need fixing?

**Comment by chid** [comment]
I believe it's part of device_tracker https://www.home-assistant.io/integrations/device_tracker/#:~:text=that%20push%20updates.-,consider_home,-180
