### ISSUE TITLE
consider_home: does not work in 1.4 and 2.0.4

### ISSUE THREAD

**Issue by smart-ctrl** [mudape/iphonedetect#85]
Seems like it's impossible to set an value below 60 sec, It still takes 55-65 seconds before it changes status to 'Away'.

**Comment by mudape** [comment]
Hi @smart-ctrl 
On 1.4 I can suspect other integrations affect the consider_home.
What is your scan_interval set to?

If you have the ability, please try installing pre-release 2.2.0 where you can set consider_home per tracked entity (15-90sec)
The scan interval is fixed to 12sec in 2.2.0
