### ISSUE TITLE
hostname2 remains

### ISSUE THREAD

**Issue by jmorris644** [mudape/iphonedetect#9]
i originally set it up using the default hostname1 and hostname2. Then I changed the configuration.yaml file to use our actual names instead of hostname1 and hostname2. 

OUr names appear in the overview page of home assistant but for some reason the hostname2 remains on the overview page of homeassistant as well. 

How can I get rid of it? It does not exist in the configuration.yaml file.

Thanks

Joe

**Comment by mudape** [comment]
Hi Joe,

Home-assistant probably has saved the device in the _/config/know_devices.yaml_ file.
You might be able to delete it via Configuration -> Entities.
Find the device and delete it.
If not, delete the device from known_devices.yaml and restart home-assistant.

Tip: There is no need to change the entities name in configuration.yaml, you can do that in Configuration. Also, consider adding the device to a Person (you can then have multiple entities handle the users state) and monitor that entity instead.

**Comment by jmorris644** [comment]
Thank you so much. It WAS in the known_devices.yaml file. It was not showing up in the config/entities though. Interesting...

Can you please explain a little more what you mean by adding the device to a Person? I have two Persons defined but am not quite following your recommendation.

THanks

Joe

**Comment by mudape** [comment]
Happy you found it :)

Regarding the Person integration, check out https://www.home-assistant.io/integrations/person/
