### ISSUE TITLE
Async issue

### ISSUE THREAD

**Issue by Senbei123** [mudape/iphonedetect#95]
Starting with 2015.3 I got the following issue:

File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/iphonedetect/__init__.py", line 86, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

**Comment by ildar170975** [comment]
> 2015.3

What is it?

**Comment by Senbei123** [comment]
Update of Home Assistant Core 2023.5.. sry.. Not Sure why I type 2015 😅

**Comment by ildar170975** [comment]
Duplicates https://github.com/mudape/iphonedetect/issues/89
Seems to be solved in the latest release.

**Comment by Senbei123** [comment]
Could be, but there is no release created jet. Last release from this plugin is from April 2021.
