### ISSUE TITLE
Can't rename device

### ISSUE THREAD

**Issue by Coder84619** [mudape/iphonedetect#96]
I'd like to rename the entity in the UI but I can't:

This entity ('device_tracker.hostname1') does not have a unique ID, therefore its settings cannot be managed from the UI. See the [documentation](https://www.home-assistant.io/faq/unique_id) for more detail.

**Comment by Animizio** [comment]
I guess it needs to be changed in the config, maybe use a friendly name or change "hostname1" to the wanted name. But sadly I dont have solved that for the too.

**Comment by Animizio** [comment]
Found a solution:

You need to add this next to "homeassistant:" inside the configuration.yml

  customize:
    device_tracker.hostname1:
      friendly_name: MyiPhoneName
    device_tracker.hostname2:
      friendly_name: MyiPhoneName2

**Comment by Coder84619** [comment]
Here's a YAML compliant example:

`homeassistant:
  customize:
    device_tracker.hostname1:
      friendly_name: DerekiPhone-Ping`
