### ISSUE TITLE
I'm currently using iphonedetect and it works fine, but I have another device_tracker based tracker that seems to conflict when I enable it at the same time, is there any way to tell the difference? For example device_tracker.iphonedetect 

### ISSUE THREAD

**Issue by MagicStarTrace** [mudape/iphonedetect#98]
device_tracker:
  - platform: iphonedetect
    consider_home: 30
    scan_interval: 12
    new_device_defaults:
      track_new_devices: true
    hosts:
      iphone12: 192.168.100.1
      iphone13: 192.168.100.12 
----------------------------------
device_tracker:
  - platform: jike_gateway_ac
    host: !secret jike_gateway_ac_host
    username: !secret jike_gateway_ac_username
    password: !secret jike_gateway_ac_password

I need to use the above two plugins in different situations How should I adjust them now?
Modify the source code or add parameters?

Thank you!

**Comment by arenasa70** [comment]
Just change the names, the entity will also change:

hosts:
iphone12_ipd: 192.168.100.1
iphone13_ipd: 192.168.100.12

your entities will be named:
device_tracker.iphone12_ipd
device_tracker.iphone13_ipd

Also check the entries in the file known_devices, they will not be renamed automatically.
